// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'default-light', 'default-dark', 'vercel-light', 'vercel-dark', 'violet-light', 'violet-dark', 'supabase-light', 'supabase-dark', 'claude-light', 'claude-dark', 'twitter-light', 'twitter-dark']
    }
}

export {}
