import {
  AccordionIcon,
  ActionsheetIcon,
  AlertDialogIcon,
  AlertIcon,
  AvatarIcon,
  BadgeIcon,
  BoxIcon,
  ButtonIcon,
  CardIcon,
  CenterIcon,
  CheckboxIcon,
  DividerIcon,
  DrawerIcon,
  FabIcon,
  FormControlIcon,
  GridIcon,
  HeadingIcon,
  HStackIcon,
  IconIcon,
  ImageIcon,
  InputIcon,
  LinkIcon,
  MenuIcon,
  ModalIcon,
  PopoverIcon,
  PortalIcon,
  PressableIcon,
  ProgressIcon,
  RadioIcon,
  SelectIcon,
  SkeletonIcon,
  SliderIcon,
  SpinnerIcon,
  SwitchIcon,
  TableIcon,
  TextareaIcon,
  TextIcon,
  ToastIcon,
  TooltipIcon,
  VStackIcon,
} from "@/components/custom/custom-icons";
import type { ComponentItem } from "@/components/custom/bottom-control-bar";

export const COMPONENTS_LIST: ComponentItem[] = [
  { title: "Accordion", path: "accordion", count: 7, icon: AccordionIcon },
  { title: "Actionsheet", path: "actionsheet", count: 9, icon: ActionsheetIcon },
  { title: "Alert", path: "alert", count: 5, icon: AlertIcon },
  { title: "AlertDialog", path: "alert-dialog", count: 4, icon: AlertDialogIcon },
  { title: "Avatar", path: "avatar", count: 9, icon: AvatarIcon },
  { title: "Badge", path: "badge", count: 3, icon: BadgeIcon },
  { title: "Box", path: "box", count: 1, icon: BoxIcon },
  { title: "Button", path: "button", count: 6, icon: ButtonIcon },
  { title: "Calendar", path: "calendar", count: 7 },
  { title: "Card", path: "card", count: 5, icon: CardIcon },
  { title: "Center", path: "center", count: 1, icon: CenterIcon },
  { title: "Checkbox", path: "checkbox", count: 9, icon: CheckboxIcon },
  { title: "DateTimePicker", path: "date-time-picker", count: 4 },
  { title: "Divider", path: "divider", count: 5, icon: DividerIcon },
  { title: "Drawer", path: "drawer", count: 3, icon: DrawerIcon },
  { title: "Fab", path: "fab", count: 5, icon: FabIcon },
  { title: "FormControl", path: "form-control", count: 7, icon: FormControlIcon },
  { title: "Grid", path: "grid", count: 5, icon: GridIcon },
  { title: "Heading", path: "heading", count: 2, icon: HeadingIcon },
  { title: "HStack", path: "hstack", count: 2, icon: HStackIcon },
  { title: "Icon", path: "icon", count: 4, icon: IconIcon },
  { title: "Image", path: "image", count: 2, icon: ImageIcon },
  { title: "Image Viewer", path: "image-viewer", count: 3 },
  { title: "Input", path: "input", count: 3, icon: InputIcon },
  { title: "Link", path: "link", count: 3, icon: LinkIcon },
  { title: "Menu", path: "menu", count: 3, icon: MenuIcon },
  { title: "Modal", path: "modal", count: 5, icon: ModalIcon },
  { title: "Popover", path: "popover", count: 5, icon: PopoverIcon },
  { title: "Portal", path: "portal", count: 1, icon: PortalIcon },
  { title: "Pressable", path: "pressable", count: 2, icon: PressableIcon },
  { title: "Progress", path: "progress", count: 4, icon: ProgressIcon },
  { title: "Radio", path: "radio", count: 9, icon: RadioIcon },
  { title: "Select", path: "select", count: 2, icon: SelectIcon },
  { title: "Skeleton", path: "skeleton", count: 2, icon: SkeletonIcon },
  { title: "Slider", path: "slider", count: 1, icon: SliderIcon },
  { title: "Spinner", path: "spinner", count: 3, icon: SpinnerIcon },
  { title: "Switch", path: "switch", count: 3, icon: SwitchIcon },
  { title: "Table", path: "table", count: 5, icon: TableIcon },
  { title: "Text", path: "text", count: 2, icon: TextIcon },
  { title: "Textarea", path: "textarea", count: 2, icon: TextareaIcon },
  { title: "Toast", path: "toast", count: 5, icon: ToastIcon },
  { title: "Tooltip", path: "tooltip", count: 3, icon: TooltipIcon },
  { title: "VStack", path: "vstack", count: 2, icon: VStackIcon }
];

export const getComponentByPath = (path: string): ComponentItem | undefined => {
  return COMPONENTS_LIST.find((c) => c.path === path);
};

