import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import { GluestackUIProvider } from '@/components/ui/gluestack-ui-provider';
import { getThemeFromCookies } from '@/lib/theme/cookies';
import { getThemeScript, getSystemThemeListenerScript } from '@/lib/theme';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the theme from cookies on the server
  const colorMode = await getThemeFromCookies();

  // Determine the initial class for SSR
  // For 'system' mode, we default to dark on server (script will fix on client)
  const initialClass = colorMode === 'system' ? 'dark' : colorMode;

  return (
    <html
      lang="en"
      className={initialClass}
      style={{ colorScheme: initialClass }}
    >
      <head>
        {/* Inline script to prevent flash of wrong theme */}
        <script
          dangerouslySetInnerHTML={{
            __html: getThemeScript(colorMode),
          }}
        />
        {/* Script to handle system theme changes */}
        <script
          dangerouslySetInnerHTML={{
            __html: getSystemThemeListenerScript(),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GluestackUIProvider>{children}</GluestackUIProvider>
      </body>
    </html>
  );
}
