module.exports = {
  stories: [
    '../src/overview/**/*.stories.mdx',
    '../src/overview/**/*.stories.@(js|jsx|ts|tsx)',
    '../src/getting-started/**/*.stories.mdx',
    '../src/getting-started/**/*.stories.@(js|jsx|ts|tsx)',
    '../src/api/**/*.stories.mdx',
    '../src/api/**/*.stories.@(js|jsx|ts|tsx)',
    '../src/configuration/**/*.stories.mdx',
    '../src/configuration/**/*.stories.@(js|jsx|ts|tsx)',
    '../src/advanced/**/*.stories.mdx',
    '../src/advanced/**/*.stories.@(js|jsx|ts|tsx)',
    // '../src/components/**/*.stories.mdx',
    // '../src/components/**/*.stories.@(js|jsx|ts|tsx)',
    // '../src/recipes/**/*.stories.mdx',
    // '../src/recipes/**/*.stories.@(js|jsx|ts|tsx)',
    // '../src/hooks/*.stories.mdx',
    // '../src/hooks/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    'storybook-dark-mode',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-react-native-web',
    '@storybook/addon-docs',
  ],
  framework: '@storybook/react',
  typescript: {
    reactDocgen: 'none',
  },
};
