export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  docs: {
    // inlineStories: false,
  },
  options: {
    storySort: {
      method: '',
      order: [
        'Overview',
        ['Introduction', 'API'],
        'Getting Started',
        ['Installation', 'Styling', 'Accessibility'],
        'Components',
        [
          'Actionsheet',
          'AlertDialog',
          'Avatar',
          'Button',
          'ButtonGroup',
          'Checkbox',
          'Divider',
          'Fab',
          'FormControl',
          'HStack',
          'Icon',
          'IconButton',
          'Input',
          'InputGroup',
          'Link',
          'Menu',
          'Modal',
          'Overlay',
          'Popover',
          'Pressable',
          'Progress',
          'Provider',
          'Radio',
          'Select',
          'Slider',
          'Spinner',
          'Stack',
          'Switch',
          'TextArea',
          'Toast',
          'Tooltip',
          'Transitions',
          'VStack',
        ],
      ],
    },
  },
};
