export const componentsImportMap = {
  'accordion': [
    'Accordion',
    'AccordionItem',
    'AccordionHeader',
    'AccordionTrigger',
    'AccordionTitleText',
    'AccordionContentText',
    'AccordionIcon',
    'AccordionContent',
  ],
  'actionsheet': [
    'Actionsheet',
    'ActionsheetContent',
    'ActionsheetItem',
    'ActionsheetItemText',
    'ActionsheetDragIndicator',
    'ActionsheetDragIndicatorWrapper',
    'ActionsheetBackdrop',
    'ActionsheetScrollView',
    'ActionsheetVirtualizedList',
    'ActionsheetFlatList',
    'ActionsheetSectionList',
    'ActionsheetSectionHeaderText',
    'ActionsheetIcon',
  ],
  'bottomsheet': [
    'BottomSheet',
    'BottomSheetPortal',
    'BottomSheetTrigger',
    'BottomSheetBackdrop',
    'BottomSheetDragIndicator',
    'BottomSheetContent',
    'BottomSheetItem',
    'BottomSheetItemText',
    'BottomSheetScrollView',
    'BottomSheetFlatList',
    'BottomSheetSectionList',
    'BottomSheetTextInput',
  ],
  'alert': ['Alert', 'AlertText', 'AlertIcon'],
  'alert-dialog': [
    'AlertDialog',
    'AlertDialogContent',
    'AlertDialogCloseButton',
    'AlertDialogHeader',
    'AlertDialogFooter',
    'AlertDialogBody',
    'AlertDialogBackdrop',
  ],
  'avatar': [
    'Avatar',
    'AvatarBadge',
    'AvatarFallbackText',
    'AvatarImage',
    'AvatarGroup',
  ],
  'badge': ['Badge', 'BadgeIcon', 'BadgeText'],
  'box': ['Box'],
  'button': [
    'Button',
    'ButtonText',
    'ButtonSpinner',
    'ButtonIcon',
    'ButtonGroup',
  ],
  'card': ['Card'],
  'center': ['Center'],
  'checkbox': [
    'Checkbox',
    'CheckboxIndicator',
    'CheckboxLabel',
    'CheckboxIcon',
    'CheckboxGroup',
  ],
  'divider': ['Divider'],
  'drawer': [
    'Drawer',
    'DrawerBackdrop',
    'DrawerContent',
    'DrawerCloseButton',
    'DrawerHeader',
    'DrawerBody',
    'DrawerFooter',
  ],
  'fab': ['Fab', 'FabLabel', 'FabIcon'],
  'flat-list': ['FlatList'],
  'form-control': [
    'FormControl',
    'FormControlError',
    'FormControlErrorText',
    'FormControlErrorIcon',
    'FormControlLabel',
    'FormControlLabelText',
    'FormControlLabelAstrick',
    'FormControlHelper',
    'FormControlHelperText',
  ],
  'grid': ['Grid', 'GridItem'],
  'gluestack-ui-provider': ['GluestackUIProvider'],
  'heading': ['Heading'],
  'hstack': ['HStack'],
  'image': ['Image'],
  'image-background': ['ImageBackground'],
  'input': ['Input', 'InputField', 'InputIcon', 'InputSlot'],
  'input-accessory-view': ['InputAccessoryView'],
  'keyboard-avoiding-view': ['KeyboardAvoidingView'],
  'link': ['Link', 'LinkText'],
  'menu': ['Menu', 'MenuItem', 'MenuItemLabel', 'MenuSeparator'],
  'modal': [
    'Modal',
    'ModalBackdrop',
    'ModalContent',
    'ModalCloseButton',
    'ModalHeader',
    'ModalBody',
    'ModalFooter',
  ],
  'popover': [
    'Popover',
    'PopoverBackdrop',
    'PopoverArrow',
    'PopoverCloseButton',
    'PopoverFooter',
    'PopoverHeader',
    'PopoverBody',
    'PopoverContent',
  ],
  'pressable': ['Pressable'],
  'progress': ['Progress', 'ProgressFilledTrack'],
  'radio': ['Radio', 'RadioGroup', 'RadioIndicator', 'RadioLabel', 'RadioIcon'],
  'refresh-control': ['RefreshControl'],
  'safe-area-view': ['SafeAreaView'],
  'scroll-view': ['ScrollView'],
  'section-list': ['SectionList'],
  'select': [
    'Select',
    'SelectTrigger',
    'SelectInput',
    'SelectIcon',
    'SelectPortal',
    'SelectBackdrop',
    'SelectContent',
    'SelectDragIndicator',
    'SelectDragIndicatorWrapper',
    'SelectItem',
    'SelectItemText',
    'SelectScrollView',
    'SelectVirtualizedList',
    'SelectFlatList',
    'SelectSectionList',
    'SelectSectionHeaderText',
  ],
  'skeleton': ['Skeleton', 'SkeletonText'],
  'slider': ['Slider', 'SliderThumb', 'SliderTrack', 'SliderFilledTrack'],
  'spinner': ['Spinner'],
  'statusbar': ['StatusBar'],
  'switch': ['Switch'],
  'table': [
    'Table',
    'TableHeader',
    'TableBody',
    'TableFooter',
    'TableHead',
    'TableRow',
    'TableData',
    'TableCaption',
  ],
  'text': ['Text'],
  'textarea': ['Textarea', 'TextareaInput'],
  'toast': ['useToast', 'Toast', 'ToastTitle', 'ToastDescription'],
  'tooltip': ['Tooltip', 'TooltipContent', 'TooltipText'],
  'view': ['View'],
  'virtualized-list': ['VirtualizedList'],
  'vstack': ['VStack'],
  'icon': [
    'Icon',
    'createIcon',
    'AddIcon',
    'AlertCircleIcon',
    'ArrowUpIcon',
    'ArrowDownIcon',
    'ArrowRightIcon',
    'ArrowLeftIcon',
    'AtSignIcon',
    'BellIcon',
    'CalendarDaysIcon',
    'CheckIcon',
    'CheckCircleIcon',
    'ChevronUpIcon',
    'ChevronDownIcon',
    'ChevronLeftIcon',
    'ChevronRightIcon',
    'ChevronsLeftIcon',
    'ChevronsRightIcon',
    'ChevronsUpDownIcon',
    'CircleIcon',
    'ClockIcon',
    'CloseIcon',
    'CloseCircleIcon',
    'CopyIcon',
    'DownloadIcon',
    'EditIcon',
    'EyeIcon',
    'EyeOffIcon',
    'FavouriteIcon',
    'GlobeIcon',
    'GripVerticalIcon',
    'HelpCircleIcon',
    'InfoIcon',
    'LinkIcon',
    'ExternalLinkIcon',
    'LoaderIcon',
    'LockIcon',
    'MailIcon',
    'MenuIcon',
    'MessageCircleIcon',
    'MoonIcon',
    'PaperclipIcon',
    'PhoneIcon',
    'PlayIcon',
    'RemoveIcon',
    'RepeatIcon',
    'Repeat1Icon',
    'SearchIcon',
    'SettingsIcon',
    'ShareIcon',
    'SlashIcon',
    'StarIcon',
    'SunIcon',
    'ThreeDotsIcon',
    'TrashIcon',
    'UnlockIcon',
  ],
  'tailwindcss/colors': ['colors'],
  'react-native': ['Platform'],
  'react': ['React'],
  'react-native-svg': ['Path', 'Rect'],
};
