import { SectionWrapper as SectionWrapperMain } from './SectionWrapper';
import { Title } from './Title';
import { Description } from './Description';
import { Body } from './Body';
const SectionWrapperTemp = SectionWrapperMain as any;
SectionWrapperTemp.Title = Title;
SectionWrapperTemp.Description = Description;
SectionWrapperTemp.Body = Body;
const SectionWrapper = SectionWrapperTemp;
export { SectionWrapper };
